# Generated by Django 5.1.5 on 2026-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchaseitem_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
    ]
