# Generated by Django 5.0.6 on 2026-07-03 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('sales', 'مبيعات'), ('purchases', 'مشتريات'), ('inventory', 'مخزون'), ('customers', 'عملاء'), ('suppliers', 'موردين'), ('finance', 'مالية'), ('profit_loss', 'أرباح وخسائر')], max_length=50, verbose_name='نوع التقرير')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='الفلاتر')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسار الملف')),
                ('format', models.CharField(default='json', max_length=10, verbose_name='صيغة التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل تقرير',
                'verbose_name_plural': 'سجل التقارير',
                'db_table': 'report_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
