# Generated by Django 5.0.6 on 2026-07-04 00:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ'), ('stock_alert', 'تنبيه مخزون'), ('payment_due', 'موعد دفع'), ('collection_due', 'موعد تحصيل'), ('order_received', 'استلام طلب'), ('system', 'نظام')], default='info', max_length=20, verbose_name='نوع الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('is_sent', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='الرابط')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المرجع')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='معرف المرجع')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'بريد إلكتروني'), ('push', 'إشعار تطبيق'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب')], max_length=20, verbose_name='قناة الإرسال')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='الحالة')),
                ('response', models.TextField(blank=True, null=True, verbose_name='الاستجابة')),
                ('error', models.TextField(blank=True, null=True, verbose_name='الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجل الإشعارات',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات')),
                ('enable_email', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('enable_push', models.BooleanField(default=True, verbose_name='إشعارات التطبيق')),
                ('stock_alert', models.BooleanField(default=True, verbose_name='تنبيهات المخزون')),
                ('payment_due', models.BooleanField(default=True, verbose_name='مواعيد الدفع')),
                ('collection_due', models.BooleanField(default=True, verbose_name='مواعيد التحصيل')),
                ('order_received', models.BooleanField(default=True, verbose_name='استلام الطلبات')),
                ('system_updates', models.BooleanField(default=True, verbose_name='تحديثات النظام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx'),
        ),
    ]
