# Generated by Django 5.1.5 on 2026-07-11 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_remove_notification_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='shipment_due',
            field=models.BooleanField(default=True, verbose_name='مواعيد الشحنات'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('error', 'خطأ'), ('payment_due', 'موعد دفع'), ('collection_due', 'موعد تحصيل'), ('shipment_due', 'موعد شحنة'), ('shipment_received', 'تم استلام شحنة'), ('stock_alert', 'تنبيه مخزون'), ('system', 'نظام'), ('order_created', 'طلب جديد'), ('order_confirmed', 'تم تأكيد الطلب')], default='info', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'is_read'], name='notificatio_notific_72d27e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['due_date'], name='notificatio_due_dat_8a5d28_idx'),
        ),
    ]
