# Generated by Django 5.1.5 on 2026-07-06 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(-9999999999.99), django.core.validators.MaxValueValidator(9999999999.99)], verbose_name='الرصيد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999.99)], verbose_name='حد الائتمان'),
        ),
    ]
