# Generated by Django 5.1.5 on 2026-07-04 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العنصر')),
                ('widget_type', models.CharField(choices=[('summary', 'ملخص عام'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('inventory', 'المخزون'), ('finance', 'المالية'), ('customers', 'العملاء'), ('suppliers', 'الموردين'), ('products', 'المنتجات'), ('chart', 'رسم بياني'), ('table', 'جدول')], max_length=50, verbose_name='نوع العنصر')),
                ('config', models.JSONField(default=dict, verbose_name='الإعدادات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عنصر لوحة التحكم',
                'verbose_name_plural': 'عناصر لوحة التحكم',
                'db_table': 'dashboard_widgets',
                'ordering': ['order'],
            },
        ),
    ]
