# Generated by Django 5.0.6 on 2026-07-04 00:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الحساب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('name_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الحساب بالعربية')),
                ('account_type', models.CharField(choices=[('asset', 'أصل'), ('liability', 'خصم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيراد'), ('expense', 'مصروف')], max_length=20, verbose_name='نوع الحساب')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.account', verbose_name='الحساب الرئيسي')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'db_table': 'accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('cash_in', 'إيداع نقدي'), ('cash_out', 'سحب نقدي'), ('transfer', 'تحويل')], max_length=20, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المرجع')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='معرف المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معاملة نقدية',
                'verbose_name_plural': 'المعاملات النقدية',
                'db_table': 'cash_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإيداعات')),
                ('cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المسحوبات')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الختامي')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المبيعات')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المصروفات')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الإيرادات')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='صافي الربح')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إغلاق يومي',
                'verbose_name_plural': 'الإغلاق اليومي',
                'db_table': 'daily_closings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('utilities', 'مرافق'), ('salaries', 'رواتب'), ('supplies', 'مستلزمات'), ('maintenance', 'صيانة'), ('transport', 'نقل'), ('marketing', 'تسويق'), ('other', 'أخرى')], max_length=20, verbose_name='الفئة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('payment_method', models.CharField(default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='الفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'db_table': 'expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sales', 'مبيعات'), ('services', 'خدمات'), ('interest', 'فوائد'), ('other', 'أخرى')], max_length=20, verbose_name='الفئة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('payment_method', models.CharField(default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='incomes/', verbose_name='الفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إيراد',
                'verbose_name_plural': 'الإيرادات',
                'db_table': 'incomes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(max_length=20, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المرجع')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='معرف المرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيد اليومية',
                'db_table': 'journal_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دائن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'تفصيل قيد',
                'verbose_name_plural': 'تفاصيل القيد',
                'db_table': 'journal_lines',
            },
        ),
    ]
