# Generated by Django 5.1.5 on 2026-07-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الفاتورة'),
        ),
    ]
